name: Build
on:
  push:
    branches:
    - main
    - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Lint code
      run: |
        pip install pre-commit
        pre-commit run --all-files
    - name: Test code
      run: |
        pip install .[test]
        pytest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
